package com.hengkang.app.mappers;

import com.hengkang.app.models.CorpLogin;

public interface CorpLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CORPLOGIN
     *
     * @mbggenerated
     */
    int insert(CorpLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CORPLOGIN
     *
     * @mbggenerated
     */
    int insertSelective(CorpLogin record);
}