package com.hengkang.app.mappers;

import com.hengkang.app.annotation.MyBatisDao;
import com.hengkang.app.models.YsSmsSummary;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisDao
public interface YsSmsSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YS_SMS_SUMMARY
     *
     * @mbggenerated
     */
    int insert(YsSmsSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YS_SMS_SUMMARY
     *
     * @mbggenerated
     */
    int insertSelective(YsSmsSummary record);

    List<YsSmsSummary> selectByParam(@Param("param")String param);

    int updateByParam(String param);

}