package com.hengkang.app.models;

import java.util.Date;

public class CorpLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.CORPID
     *
     * @mbggenerated
     */
    private Short corpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.LOGINID
     *
     * @mbggenerated
     */
    private Short loginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.LOGINNAME
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.ERRLOGIN
     *
     * @mbggenerated
     */
    private Short errlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.CANUSEDATE
     *
     * @mbggenerated
     */
    private Date canusedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.BUSINESSNAME
     *
     * @mbggenerated
     */
    private String businessname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.STATE
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.LASTLOGINTIME
     *
     * @mbggenerated
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.PARENTID
     *
     * @mbggenerated
     */
    private Short parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORPLOGIN.PRICE
     *
     * @mbggenerated
     */
    private Short price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.CORPID
     *
     * @return the value of CORPLOGIN.CORPID
     *
     * @mbggenerated
     */
    public Short getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.CORPID
     *
     * @param corpid the value for CORPLOGIN.CORPID
     *
     * @mbggenerated
     */
    public void setCorpid(Short corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.LOGINID
     *
     * @return the value of CORPLOGIN.LOGINID
     *
     * @mbggenerated
     */
    public Short getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.LOGINID
     *
     * @param loginid the value for CORPLOGIN.LOGINID
     *
     * @mbggenerated
     */
    public void setLoginid(Short loginid) {
        this.loginid = loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.LOGINNAME
     *
     * @return the value of CORPLOGIN.LOGINNAME
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.LOGINNAME
     *
     * @param loginname the value for CORPLOGIN.LOGINNAME
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.PASSWORD
     *
     * @return the value of CORPLOGIN.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.PASSWORD
     *
     * @param password the value for CORPLOGIN.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.ERRLOGIN
     *
     * @return the value of CORPLOGIN.ERRLOGIN
     *
     * @mbggenerated
     */
    public Short getErrlogin() {
        return errlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.ERRLOGIN
     *
     * @param errlogin the value for CORPLOGIN.ERRLOGIN
     *
     * @mbggenerated
     */
    public void setErrlogin(Short errlogin) {
        this.errlogin = errlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.CANUSEDATE
     *
     * @return the value of CORPLOGIN.CANUSEDATE
     *
     * @mbggenerated
     */
    public Date getCanusedate() {
        return canusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.CANUSEDATE
     *
     * @param canusedate the value for CORPLOGIN.CANUSEDATE
     *
     * @mbggenerated
     */
    public void setCanusedate(Date canusedate) {
        this.canusedate = canusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.BUSINESSNAME
     *
     * @return the value of CORPLOGIN.BUSINESSNAME
     *
     * @mbggenerated
     */
    public String getBusinessname() {
        return businessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.BUSINESSNAME
     *
     * @param businessname the value for CORPLOGIN.BUSINESSNAME
     *
     * @mbggenerated
     */
    public void setBusinessname(String businessname) {
        this.businessname = businessname == null ? null : businessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.STATE
     *
     * @return the value of CORPLOGIN.STATE
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.STATE
     *
     * @param state the value for CORPLOGIN.STATE
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.LASTLOGINTIME
     *
     * @return the value of CORPLOGIN.LASTLOGINTIME
     *
     * @mbggenerated
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.LASTLOGINTIME
     *
     * @param lastlogintime the value for CORPLOGIN.LASTLOGINTIME
     *
     * @mbggenerated
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.PARENTID
     *
     * @return the value of CORPLOGIN.PARENTID
     *
     * @mbggenerated
     */
    public Short getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.PARENTID
     *
     * @param parentid the value for CORPLOGIN.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Short parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORPLOGIN.PRICE
     *
     * @return the value of CORPLOGIN.PRICE
     *
     * @mbggenerated
     */
    public Short getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORPLOGIN.PRICE
     *
     * @param price the value for CORPLOGIN.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Short price) {
        this.price = price;
    }
}