package com.hengkang.app.models;

import java.util.Date;

public class Mtsend_Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.OIDNEW
     *
     * @mbggenerated
     */
    private Integer oidnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.OIDOLD
     *
     * @mbggenerated
     */
    private Integer oidold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.PUTINTIME
     *
     * @mbggenerated
     */
    private Date putintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.LOGINID
     *
     * @mbggenerated
     */
    private Integer loginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.MSGCONT
     *
     * @mbggenerated
     */
    private String msgcont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.UC
     *
     * @mbggenerated
     */
    private String uc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.CHANNELID
     *
     * @mbggenerated
     */
    private Integer channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.PRI
     *
     * @mbggenerated
     */
    private Integer pri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.PKNUM
     *
     * @mbggenerated
     */
    private Integer pknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.PKTOTAL
     *
     * @mbggenerated
     */
    private Integer pktotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.STATE
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.FEENUM
     *
     * @mbggenerated
     */
    private Integer feenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.SUBMITMSGID
     *
     * @mbggenerated
     */
    private String submitmsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.RPTSTATE
     *
     * @mbggenerated
     */
    private Integer rptstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.RPTINFO
     *
     * @mbggenerated
     */
    private String rptinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.RPTRECVTIME
     *
     * @mbggenerated
     */
    private Date rptrecvtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.SUBMITTIME
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.CHPRI
     *
     * @mbggenerated
     */
    private Integer chpri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTSEND_INFO.LINKID
     *
     * @mbggenerated
     */
    private Integer linkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.OIDNEW
     *
     * @return the value of MTSEND_INFO.OIDNEW
     *
     * @mbggenerated
     */
    public Integer getOidnew() {
        return oidnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.OIDNEW
     *
     * @param oidnew the value for MTSEND_INFO.OIDNEW
     *
     * @mbggenerated
     */
    public void setOidnew(Integer oidnew) {
        this.oidnew = oidnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.OIDOLD
     *
     * @return the value of MTSEND_INFO.OIDOLD
     *
     * @mbggenerated
     */
    public Integer getOidold() {
        return oidold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.OIDOLD
     *
     * @param oidold the value for MTSEND_INFO.OIDOLD
     *
     * @mbggenerated
     */
    public void setOidold(Integer oidold) {
        this.oidold = oidold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.PUTINTIME
     *
     * @return the value of MTSEND_INFO.PUTINTIME
     *
     * @mbggenerated
     */
    public Date getPutintime() {
        return putintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.PUTINTIME
     *
     * @param putintime the value for MTSEND_INFO.PUTINTIME
     *
     * @mbggenerated
     */
    public void setPutintime(Date putintime) {
        this.putintime = putintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.LOGINID
     *
     * @return the value of MTSEND_INFO.LOGINID
     *
     * @mbggenerated
     */
    public Integer getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.LOGINID
     *
     * @param loginid the value for MTSEND_INFO.LOGINID
     *
     * @mbggenerated
     */
    public void setLoginid(Integer loginid) {
        this.loginid = loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.PHONE
     *
     * @return the value of MTSEND_INFO.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.PHONE
     *
     * @param phone the value for MTSEND_INFO.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.MSGCONT
     *
     * @return the value of MTSEND_INFO.MSGCONT
     *
     * @mbggenerated
     */
    public String getMsgcont() {
        return msgcont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.MSGCONT
     *
     * @param msgcont the value for MTSEND_INFO.MSGCONT
     *
     * @mbggenerated
     */
    public void setMsgcont(String msgcont) {
        this.msgcont = msgcont == null ? null : msgcont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.UC
     *
     * @return the value of MTSEND_INFO.UC
     *
     * @mbggenerated
     */
    public String getUc() {
        return uc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.UC
     *
     * @param uc the value for MTSEND_INFO.UC
     *
     * @mbggenerated
     */
    public void setUc(String uc) {
        this.uc = uc == null ? null : uc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.CHANNELID
     *
     * @return the value of MTSEND_INFO.CHANNELID
     *
     * @mbggenerated
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.CHANNELID
     *
     * @param channelid the value for MTSEND_INFO.CHANNELID
     *
     * @mbggenerated
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.PRI
     *
     * @return the value of MTSEND_INFO.PRI
     *
     * @mbggenerated
     */
    public Integer getPri() {
        return pri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.PRI
     *
     * @param pri the value for MTSEND_INFO.PRI
     *
     * @mbggenerated
     */
    public void setPri(Integer pri) {
        this.pri = pri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.PKNUM
     *
     * @return the value of MTSEND_INFO.PKNUM
     *
     * @mbggenerated
     */
    public Integer getPknum() {
        return pknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.PKNUM
     *
     * @param pknum the value for MTSEND_INFO.PKNUM
     *
     * @mbggenerated
     */
    public void setPknum(Integer pknum) {
        this.pknum = pknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.PKTOTAL
     *
     * @return the value of MTSEND_INFO.PKTOTAL
     *
     * @mbggenerated
     */
    public Integer getPktotal() {
        return pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.PKTOTAL
     *
     * @param pktotal the value for MTSEND_INFO.PKTOTAL
     *
     * @mbggenerated
     */
    public void setPktotal(Integer pktotal) {
        this.pktotal = pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.STATE
     *
     * @return the value of MTSEND_INFO.STATE
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.STATE
     *
     * @param state the value for MTSEND_INFO.STATE
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.FEENUM
     *
     * @return the value of MTSEND_INFO.FEENUM
     *
     * @mbggenerated
     */
    public Integer getFeenum() {
        return feenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.FEENUM
     *
     * @param feenum the value for MTSEND_INFO.FEENUM
     *
     * @mbggenerated
     */
    public void setFeenum(Integer feenum) {
        this.feenum = feenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.SUBMITMSGID
     *
     * @return the value of MTSEND_INFO.SUBMITMSGID
     *
     * @mbggenerated
     */
    public String getSubmitmsgid() {
        return submitmsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.SUBMITMSGID
     *
     * @param submitmsgid the value for MTSEND_INFO.SUBMITMSGID
     *
     * @mbggenerated
     */
    public void setSubmitmsgid(String submitmsgid) {
        this.submitmsgid = submitmsgid == null ? null : submitmsgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.RPTSTATE
     *
     * @return the value of MTSEND_INFO.RPTSTATE
     *
     * @mbggenerated
     */
    public Integer getRptstate() {
        return rptstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.RPTSTATE
     *
     * @param rptstate the value for MTSEND_INFO.RPTSTATE
     *
     * @mbggenerated
     */
    public void setRptstate(Integer rptstate) {
        this.rptstate = rptstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.RPTINFO
     *
     * @return the value of MTSEND_INFO.RPTINFO
     *
     * @mbggenerated
     */
    public String getRptinfo() {
        return rptinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.RPTINFO
     *
     * @param rptinfo the value for MTSEND_INFO.RPTINFO
     *
     * @mbggenerated
     */
    public void setRptinfo(String rptinfo) {
        this.rptinfo = rptinfo == null ? null : rptinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.RPTRECVTIME
     *
     * @return the value of MTSEND_INFO.RPTRECVTIME
     *
     * @mbggenerated
     */
    public Date getRptrecvtime() {
        return rptrecvtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.RPTRECVTIME
     *
     * @param rptrecvtime the value for MTSEND_INFO.RPTRECVTIME
     *
     * @mbggenerated
     */
    public void setRptrecvtime(Date rptrecvtime) {
        this.rptrecvtime = rptrecvtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.SUBMITTIME
     *
     * @return the value of MTSEND_INFO.SUBMITTIME
     *
     * @mbggenerated
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.SUBMITTIME
     *
     * @param submittime the value for MTSEND_INFO.SUBMITTIME
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.CHPRI
     *
     * @return the value of MTSEND_INFO.CHPRI
     *
     * @mbggenerated
     */
    public Integer getChpri() {
        return chpri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.CHPRI
     *
     * @param chpri the value for MTSEND_INFO.CHPRI
     *
     * @mbggenerated
     */
    public void setChpri(Integer chpri) {
        this.chpri = chpri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTSEND_INFO.LINKID
     *
     * @return the value of MTSEND_INFO.LINKID
     *
     * @mbggenerated
     */
    public Integer getLinkid() {
        return linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTSEND_INFO.LINKID
     *
     * @param linkid the value for MTSEND_INFO.LINKID
     *
     * @mbggenerated
     */
    public void setLinkid(Integer linkid) {
        this.linkid = linkid;
    }
}