package com.hengkang.app.models;

public class Traffic_Statistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.STATDATE
     *
     * @mbggenerated
     */
    private String statdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.CHTYPE
     *
     * @mbggenerated
     */
    private Integer chtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.CHANNELID
     *
     * @mbggenerated
     */
    private Integer channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.MTNUM
     *
     * @mbggenerated
     */
    private Integer mtnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.FEENUM
     *
     * @mbggenerated
     */
    private Integer feenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.FEESUCCESS
     *
     * @mbggenerated
     */
    private Integer feesuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.FEEFAILURE
     *
     * @mbggenerated
     */
    private Integer feefailure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.LOGINID
     *
     * @mbggenerated
     */
    private Integer loginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRAFFIC_STATISTICS.CORPID
     *
     * @mbggenerated
     */
    private Integer corpid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.STATDATE
     *
     * @return the value of TRAFFIC_STATISTICS.STATDATE
     *
     * @mbggenerated
     */
    public String getStatdate() {
        return statdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.STATDATE
     *
     * @param statdate the value for TRAFFIC_STATISTICS.STATDATE
     *
     * @mbggenerated
     */
    public void setStatdate(String statdate) {
        this.statdate = statdate == null ? null : statdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.CHTYPE
     *
     * @return the value of TRAFFIC_STATISTICS.CHTYPE
     *
     * @mbggenerated
     */
    public Integer getChtype() {
        return chtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.CHTYPE
     *
     * @param chtype the value for TRAFFIC_STATISTICS.CHTYPE
     *
     * @mbggenerated
     */
    public void setChtype(Integer chtype) {
        this.chtype = chtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.CHANNELID
     *
     * @return the value of TRAFFIC_STATISTICS.CHANNELID
     *
     * @mbggenerated
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.CHANNELID
     *
     * @param channelid the value for TRAFFIC_STATISTICS.CHANNELID
     *
     * @mbggenerated
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.TYPE
     *
     * @return the value of TRAFFIC_STATISTICS.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.TYPE
     *
     * @param type the value for TRAFFIC_STATISTICS.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.MTNUM
     *
     * @return the value of TRAFFIC_STATISTICS.MTNUM
     *
     * @mbggenerated
     */
    public Integer getMtnum() {
        return mtnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.MTNUM
     *
     * @param mtnum the value for TRAFFIC_STATISTICS.MTNUM
     *
     * @mbggenerated
     */
    public void setMtnum(Integer mtnum) {
        this.mtnum = mtnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.FEENUM
     *
     * @return the value of TRAFFIC_STATISTICS.FEENUM
     *
     * @mbggenerated
     */
    public Integer getFeenum() {
        return feenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.FEENUM
     *
     * @param feenum the value for TRAFFIC_STATISTICS.FEENUM
     *
     * @mbggenerated
     */
    public void setFeenum(Integer feenum) {
        this.feenum = feenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.FEESUCCESS
     *
     * @return the value of TRAFFIC_STATISTICS.FEESUCCESS
     *
     * @mbggenerated
     */
    public Integer getFeesuccess() {
        return feesuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.FEESUCCESS
     *
     * @param feesuccess the value for TRAFFIC_STATISTICS.FEESUCCESS
     *
     * @mbggenerated
     */
    public void setFeesuccess(Integer feesuccess) {
        this.feesuccess = feesuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.FEEFAILURE
     *
     * @return the value of TRAFFIC_STATISTICS.FEEFAILURE
     *
     * @mbggenerated
     */
    public Integer getFeefailure() {
        return feefailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.FEEFAILURE
     *
     * @param feefailure the value for TRAFFIC_STATISTICS.FEEFAILURE
     *
     * @mbggenerated
     */
    public void setFeefailure(Integer feefailure) {
        this.feefailure = feefailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.LOGINID
     *
     * @return the value of TRAFFIC_STATISTICS.LOGINID
     *
     * @mbggenerated
     */
    public Integer getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.LOGINID
     *
     * @param loginid the value for TRAFFIC_STATISTICS.LOGINID
     *
     * @mbggenerated
     */
    public void setLoginid(Integer loginid) {
        this.loginid = loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRAFFIC_STATISTICS.CORPID
     *
     * @return the value of TRAFFIC_STATISTICS.CORPID
     *
     * @mbggenerated
     */
    public Integer getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRAFFIC_STATISTICS.CORPID
     *
     * @param corpid the value for TRAFFIC_STATISTICS.CORPID
     *
     * @mbggenerated
     */
    public void setCorpid(Integer corpid) {
        this.corpid = corpid;
    }
}