package com.hengkang.app.models;

import java.util.Date;

public class YsSmsMt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.DST_PHONE
     *
     * @mbggenerated
     */
    private String dstPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.SMS
     *
     * @mbggenerated
     */
    private String sms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.PKSESSIOINLOG
     *
     * @mbggenerated
     */
    private Integer pksessioinlog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.PKTOTAL
     *
     * @mbggenerated
     */
    private Integer pktotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.PKNUMBER
     *
     * @mbggenerated
     */
    private Integer pknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.DST_TERM
     *
     * @mbggenerated
     */
    private String dstTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.MSGID
     *
     * @mbggenerated
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.RESPTIME
     *
     * @mbggenerated
     */
    private Date resptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.REPORTTIME
     *
     * @mbggenerated
     */
    private Date reporttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.RESPMSGID
     *
     * @mbggenerated
     */
    private String respmsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_MT.REPORTRESP_TIME
     *
     * @mbggenerated
     */
    private Date reportrespTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.DST_PHONE
     *
     * @return the value of YS_SMS_MT.DST_PHONE
     *
     * @mbggenerated
     */
    public String getDstPhone() {
        return dstPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.DST_PHONE
     *
     * @param dstPhone the value for YS_SMS_MT.DST_PHONE
     *
     * @mbggenerated
     */
    public void setDstPhone(String dstPhone) {
        this.dstPhone = dstPhone == null ? null : dstPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.SMS
     *
     * @return the value of YS_SMS_MT.SMS
     *
     * @mbggenerated
     */
    public String getSms() {
        return sms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.SMS
     *
     * @param sms the value for YS_SMS_MT.SMS
     *
     * @mbggenerated
     */
    public void setSms(String sms) {
        this.sms = sms == null ? null : sms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.PKSESSIOINLOG
     *
     * @return the value of YS_SMS_MT.PKSESSIOINLOG
     *
     * @mbggenerated
     */
    public Integer getPksessioinlog() {
        return pksessioinlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.PKSESSIOINLOG
     *
     * @param pksessioinlog the value for YS_SMS_MT.PKSESSIOINLOG
     *
     * @mbggenerated
     */
    public void setPksessioinlog(Integer pksessioinlog) {
        this.pksessioinlog = pksessioinlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.PKTOTAL
     *
     * @return the value of YS_SMS_MT.PKTOTAL
     *
     * @mbggenerated
     */
    public Integer getPktotal() {
        return pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.PKTOTAL
     *
     * @param pktotal the value for YS_SMS_MT.PKTOTAL
     *
     * @mbggenerated
     */
    public void setPktotal(Integer pktotal) {
        this.pktotal = pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.PKNUMBER
     *
     * @return the value of YS_SMS_MT.PKNUMBER
     *
     * @mbggenerated
     */
    public Integer getPknumber() {
        return pknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.PKNUMBER
     *
     * @param pknumber the value for YS_SMS_MT.PKNUMBER
     *
     * @mbggenerated
     */
    public void setPknumber(Integer pknumber) {
        this.pknumber = pknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.DST_TERM
     *
     * @return the value of YS_SMS_MT.DST_TERM
     *
     * @mbggenerated
     */
    public String getDstTerm() {
        return dstTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.DST_TERM
     *
     * @param dstTerm the value for YS_SMS_MT.DST_TERM
     *
     * @mbggenerated
     */
    public void setDstTerm(String dstTerm) {
        this.dstTerm = dstTerm == null ? null : dstTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.USERID
     *
     * @return the value of YS_SMS_MT.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.USERID
     *
     * @param userid the value for YS_SMS_MT.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.MSGID
     *
     * @return the value of YS_SMS_MT.MSGID
     *
     * @mbggenerated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.MSGID
     *
     * @param msgid the value for YS_SMS_MT.MSGID
     *
     * @mbggenerated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.CREATETIME
     *
     * @return the value of YS_SMS_MT.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.CREATETIME
     *
     * @param createtime the value for YS_SMS_MT.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.RESPTIME
     *
     * @return the value of YS_SMS_MT.RESPTIME
     *
     * @mbggenerated
     */
    public Date getResptime() {
        return resptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.RESPTIME
     *
     * @param resptime the value for YS_SMS_MT.RESPTIME
     *
     * @mbggenerated
     */
    public void setResptime(Date resptime) {
        this.resptime = resptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.REPORTTIME
     *
     * @return the value of YS_SMS_MT.REPORTTIME
     *
     * @mbggenerated
     */
    public Date getReporttime() {
        return reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.REPORTTIME
     *
     * @param reporttime the value for YS_SMS_MT.REPORTTIME
     *
     * @mbggenerated
     */
    public void setReporttime(Date reporttime) {
        this.reporttime = reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.RESPMSGID
     *
     * @return the value of YS_SMS_MT.RESPMSGID
     *
     * @mbggenerated
     */
    public String getRespmsgid() {
        return respmsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.RESPMSGID
     *
     * @param respmsgid the value for YS_SMS_MT.RESPMSGID
     *
     * @mbggenerated
     */
    public void setRespmsgid(String respmsgid) {
        this.respmsgid = respmsgid == null ? null : respmsgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.STATE
     *
     * @return the value of YS_SMS_MT.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.STATE
     *
     * @param state the value for YS_SMS_MT.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_MT.REPORTRESP_TIME
     *
     * @return the value of YS_SMS_MT.REPORTRESP_TIME
     *
     * @mbggenerated
     */
    public Date getReportrespTime() {
        return reportrespTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_MT.REPORTRESP_TIME
     *
     * @param reportrespTime the value for YS_SMS_MT.REPORTRESP_TIME
     *
     * @mbggenerated
     */
    public void setReportrespTime(Date reportrespTime) {
        this.reportrespTime = reportrespTime;
    }

    private String timestr1;

    private String timestr2;

    private String timestr3;

    private String timestr4;

    private String timestr5;

    public String getTimestr1() {
        return timestr1;
    }

    public void setTimestr1(String timestr1) {
        this.timestr1 = timestr1;
    }

    public String getTimestr2() {
        return timestr2;
    }

    public void setTimestr2(String timestr2) {
        this.timestr2 = timestr2;
    }

    public String getTimestr3() {
        return timestr3;
    }

    public void setTimestr3(String timestr3) {
        this.timestr3 = timestr3;
    }

    public String getTimestr4() {
        return timestr4;
    }

    public void setTimestr4(String timestr4) {
        this.timestr4 = timestr4;
    }

    public String getTimestr5() {
        return timestr5;
    }

    public void setTimestr5(String timestr5) {
        this.timestr5 = timestr5;
    }
}