package com.hengkang.app.models;

public class YsSmsSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_SUMMARY.SRC_PHONE
     *
     * @mbggenerated
     */
    private String srcPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_SUMMARY.NUM
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_SUMMARY.RNUM
     *
     * @mbggenerated
     */
    private Integer rnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_SUMMARY.RSNUM
     *
     * @mbggenerated
     */
    private Integer rsnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YS_SMS_SUMMARY.SDATE
     *
     * @mbggenerated
     */
    private String sdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_SUMMARY.SRC_PHONE
     *
     * @return the value of YS_SMS_SUMMARY.SRC_PHONE
     *
     * @mbggenerated
     */
    public String getSrcPhone() {
        return srcPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_SUMMARY.SRC_PHONE
     *
     * @param srcPhone the value for YS_SMS_SUMMARY.SRC_PHONE
     *
     * @mbggenerated
     */
    public void setSrcPhone(String srcPhone) {
        this.srcPhone = srcPhone == null ? null : srcPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_SUMMARY.NUM
     *
     * @return the value of YS_SMS_SUMMARY.NUM
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_SUMMARY.NUM
     *
     * @param num the value for YS_SMS_SUMMARY.NUM
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_SUMMARY.RNUM
     *
     * @return the value of YS_SMS_SUMMARY.RNUM
     *
     * @mbggenerated
     */
    public Integer getRnum() {
        return rnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_SUMMARY.RNUM
     *
     * @param rnum the value for YS_SMS_SUMMARY.RNUM
     *
     * @mbggenerated
     */
    public void setRnum(Integer rnum) {
        this.rnum = rnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_SUMMARY.RSNUM
     *
     * @return the value of YS_SMS_SUMMARY.RSNUM
     *
     * @mbggenerated
     */
    public Integer getRsnum() {
        return rsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_SUMMARY.RSNUM
     *
     * @param rsnum the value for YS_SMS_SUMMARY.RSNUM
     *
     * @mbggenerated
     */
    public void setRsnum(Integer rsnum) {
        this.rsnum = rsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YS_SMS_SUMMARY.SDATE
     *
     * @return the value of YS_SMS_SUMMARY.SDATE
     *
     * @mbggenerated
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YS_SMS_SUMMARY.SDATE
     *
     * @param sdate the value for YS_SMS_SUMMARY.SDATE
     *
     * @mbggenerated
     */
    public void setSdate(String sdate) {
        this.sdate = sdate == null ? null : sdate.trim();
    }
}